FROM confluentinc/cp-kafka-connect-base:6.0.0

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"

RUN confluent-hub install --no-prompt jcustenborder/kafka-connect-twitter:0.3.33
RUN confluent-hub install --no-prompt mongodb/kafka-connect-mongodb:1.3.0
