name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build Categorizer
      run: sbt "project tweetsCategorizer" coverage test coverageReport
    - name: Build UI
      run: sbt "project tweetsUI" coverage test coverageReport
